### ISSUE TITLE
Mobile Icon

### ISSUE THREAD

**Issue by kaseyklimes** [Chrissy/tuxedo#32]
Just forked the repo in the hopes that I can lend a hand!
Is a vector version of the favicon available? Noticed the app doesn't have an icon when I add to home screen on iphone. Happy to create one from the favicon if that file is available.

**Comment by Chrissy** [comment]
Sentry issue: [INTERNAL-3](https://ddba21dd.ngrok.io/sentry/internal/issues/45/)

**Comment by Chrissy** [comment]
Sentry issue: [INTERNAL-2](https://ddba21dd.ngrok.io/sentry/internal/issues/44/)
